"""empty message

Revision ID: 5cb90c9ffc1d
Revises: 708651f48d10
Create Date: 2025-06-30 13:40:09.879745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb90c9ffc1d'
down_revision = '708651f48d10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['players.id'], name=op.f('fk_friendships_recipient_id_players')),
    sa.ForeignKeyConstraint(['requester_id'], ['players.id'], name=op.f('fk_friendships_requester_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_friendships')),
    sa.UniqueConstraint('requester_id', 'recipient_id', name='_unique_friendship')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendships')
    # ### end Alembic commands ###
