"""Initial migration

Revision ID: 708651f48d10
Revises: 
Create Date: 2025-06-30 09:49:42.392028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '708651f48d10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games'))
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players')),
    sa.UniqueConstraint('username', name=op.f('uq_players_username'))
    )
    op.create_table('game_nights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['players.id'], name=op.f('fk_game_nights_host_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_nights'))
    )
    op.create_table('player_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_player_games_game_id_games')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_games_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_games'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_games')
    op.drop_table('game_nights')
    op.drop_table('players')
    op.drop_table('games')
    # ### end Alembic commands ###
