"""Add is_public column to game_nights

Revision ID: e773082ddff7
Revises: f1db951b79d9
Create Date: 2025-07-01 07:12:26.430858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e773082ddff7'
down_revision = 'f1db951b79d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_nights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_nights', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
