"""Add GameNightInvitation and Friendship models

Revision ID: f1db951b79d9
Revises: 5cb90c9ffc1d
Create Date: 2025-06-30 13:47:55.473790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1db951b79d9'
down_revision = '5cb90c9ffc1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_night_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_night_id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['game_night_id'], ['game_nights.id'], name=op.f('fk_game_night_invitations_game_night_id_game_nights')),
    sa.ForeignKeyConstraint(['invitee_id'], ['players.id'], name=op.f('fk_game_night_invitations_invitee_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_night_invitations')),
    sa.UniqueConstraint('game_night_id', 'invitee_id', name='_unique_game_night_invitation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_night_invitations')
    # ### end Alembic commands ###
